// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/27/2026, 8:45:30 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/var/www/html/nuro-solutions/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/var/www/html/nuro-solutions/app/components/ui/**/*.{vue,js,jsx,mjs,ts,tsx}","/var/www/html/nuro-solutions/app/components/sections/**/*.{vue,js,jsx,mjs,ts,tsx}","/var/www/html/nuro-solutions/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/var/www/html/nuro-solutions/app/plugins/**/*.{js,ts,mjs}","/var/www/html/nuro-solutions/app/composables/**/*.{js,ts,mjs}","/var/www/html/nuro-solutions/app/utils/**/*.{js,ts,mjs}","/var/www/html/nuro-solutions/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/var/www/html/nuro-solutions/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/var/www/html/nuro-solutions/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/var/www/html/nuro-solutions/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;